name: Hims_Frontend_Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  buildTest:
    name: Build
    runs-on: self-hosted

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          echo "Running Installing Dependencies..."
          bun install

      - name: Run Build Script
        run: |
          echo "Running build script..."
          bun run build

      - name: Deploy to /var/www/HMIS-dev/
        run: |
          cd ~
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S rm -rf /var/www/HMIS-dev
          echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S mkdir -p /var/www/HMIS-dev
          rsync -aq --delete .next node_modules public package.json /var/www/HMIS-dev/

      - name: Run the project on background process
        run: |
          cd /var/www/HMIS-dev
          if pm2 list | grep -q "nippon-app"; then
            pm2 restart nippon-app
          else
            pm2 start bun --name "nippon-app" -- start
          fi
        env:
          CI: true
